data:
  raw_csv: googlemaps/data/locales_todos.csv
  proc_csv: googlemaps/data/MAPS_locales_procesado.csv
model:
  rf:
    n_estimators: 100
    random_state: 42
  cv:
    test_size: 0.2
logging:
  level: INFO
